// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqsftwjjjbaluskskmdu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxc2Z0d2pqamJhbHVza3NrbWR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNTA2NDEsImV4cCI6MjA1NzkyNjY0MX0.A0nXN0RiL23DHwkU0NmJ8QZ_66VEkeJdZqcFYU4Xwkc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);